"""MOEA/D."""

import copy
from typing import Any, Dict, Optional, Union

from dataclasses import dataclass

import numpy as np

from opytimizer.core.environment import Backend
from opytimizer.core import Environment
import opytimizer.math.general as g
import opytimizer.utils.exception as e
from opytimizer.core.agent import Agent
from opytimizer.core.function import Function
from opytimizer.core.optimizer import MultiObjectiveOptimizer
from opytimizer.core.space import _MultiObjectiveSpace
from opytimizer.utils import logging
from opytimizer.utils.decomposition import tchebycheff
from opytimizer.utils.operators import PolynomialMutation, SBXCrossover


logger = logging.get_logger(__name__)


class MOEAD:
    _registry = {}


    def __new__(cls, env: Optional[Environment] = None, **kwargs):
        if env is None: env = Environment().set_backend('cpu')
        if cls is MOEAD:
            target = cls._registry.get(env.backend)
            return super().__new__(target)
        return super().__new__(cls)

    def __init_subclass__(cls, backend: Backend = None, **kwargs):
        super().__init_subclass__(**kwargs)
        if backend:
            key = backend.value if hasattr(backend, 'value') else backend
            MOEAD._registry[key] = cls


@dataclass
class _MOEADDeafult(MultiObjectiveOptimizer, MOEAD, backend=Backend.CPU):
    """MOEAD class, inherited from Optimizer.

    References:
        Zhang, Q., & Li, H. (2007). MOEA/D: A multiobjective evolutionary algorithm based on decomposition.
        IEEE Transactions on evolutionary computation, 11(6), 712-731.

    """

    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        crossover_operator=None,
        mutation_operator=None,
        weight_vectors=None,
        decomposition_method =  tchebycheff,
        pbi_penalty: float = 5.0,
        **kwargs
    ) -> None:
        """Initialization method.

        Args:
            params: Contains key-value parameters to the meta-heuristics.
            crossover_operator: Crossover operator to be used.
            mutation_operator: Mutation operator to be used.
            weight_vectors: Weights generated by utils.weight_vectors methods
            decomposition_method: The decomposition method reference (avaliables methods on `utils.decompostion`)
            pbi_penalty: PBI penalty, only required with pbi `decomposition_method`

        """
        logger.info("Overriding class: Optimizer -> MOEAD (CPU).")

        super().__init__()

        self.n_subproblems = None
        self.neighborhood_size = None
        self.crossover_operator = crossover_operator or SBXCrossover()
        self.mutation_operator = mutation_operator or PolynomialMutation()
        self.decomposition_method = decomposition_method
        self.pbi_penalty = pbi_penalty
        self.weight_vectors = weight_vectors

        self.build(params)

        logger.info("Class overrided.")

    @property
    def n_subproblems(self) -> int:
        """Number of subproblems."""
        return self._n_subproblems

    @n_subproblems.setter
    def n_subproblems(self, n_subproblems: Optional[int]) -> None:
        if n_subproblems is not None:
            if not isinstance(n_subproblems, int):
                raise e.TypeError("`n_subproblems` should be an integer.")
            if n_subproblems <= 0:
                raise e.ValueError("`n_subproblems` should be higher than 0.")

        self._n_subproblems = n_subproblems


    @property
    def neighborhood_size(self) -> int:
        """Size of neighborhood T."""
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Optional[int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise e.TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise e.ValueError("`neighborhood_size` should be higher than 1.")

        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> np.ndarray:
        """Neighborhood of each subproblem."""
        return self._T
    @T.setter
    def T(self, T: np.ndarray) -> None:
        if not isinstance(T, np.ndarray):
            raise e.TypeError("`T` should be a numpy array.")
        self._T = T
        
    @property
    def pbi_penalty(self) -> float:
        return self._pbi_penalty
    
    @pbi_penalty.setter
    def pbi_penalty(self, value: float) -> None:
            if not isinstance(value, (int, float)):
                raise e.TypeError('`pbi_penalty` should be a numeric value')
            if isinstance(value, int): value = float(value)
            
            if value < 0.0:
                raise e.ValueError('`pbi_penalty` should be an non-negative number')
            
            self._pbi_penalty = value


    @property
    def weight_vectors(self) -> np.ndarray:
        """Normalized weights vector."""
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: np.ndarray) -> None:
        if not isinstance(weights, np.ndarray):
            weights = np.array(weights)
        self._weight_vectors = weights

    @property
    def z(self) -> np.ndarray:
        """Reference point."""
        return self._z

    @z.setter
    def z(self, ref: np.ndarray) -> None:
        if not isinstance(ref, np.ndarray):
            ref = np.array(ref)
        self._z = ref

    def compile(self, space: _MultiObjectiveSpace, **kwargs) -> None:
        """Compiles additional information that is used by this optimizer.

        Args:
            space: A Space object containing meta-information.

        """
        # If n_subproblems is not defined, use the number of agents
        if self.n_subproblems is None:
            self.n_subproblems = space.n_agents

        # If neighborhood_size is not defined, use 10% of the number of subproblems
        if self.neighborhood_size is None:
            self.neighborhood_size = max(2, int(np.ceil(self.n_subproblems * 0.2)))

        # Build neighborhood
        self._build_neighborhood()

        # Initialize reference point
        self.z = np.full(space.n_objectives, np.inf)

        # Initialize iteration counter
        self._is_first_iteration = True

    def _build_neighborhood(self) -> None:
        """Builds the neighborhood using Euclidean distance."""
        n = len(self.weight_vectors)
        distances = np.zeros((n, n))

        for i in range(n):
            for j in range(n):
                distances[i, j] = g.euclidean_distance(
                    self.weight_vectors[i], self.weight_vectors[j]
                )

        self.T = np.argsort(distances, axis=1)[:, : self.neighborhood_size]

    def _select_neighbors(self, index: int, space: _MultiObjectiveSpace) -> np.ndarray:
        """Selects neighbors for reproduction.

        Args:
            index: Current agent index.
            space: Space containing the population.

        Returns:
            (np.ndarray): Selected neighbor indices.

        """
        # Map the agent index to the subproblem index
        subproblem_idx = index % self.n_subproblems
        neighbors = self.T[subproblem_idx]

        # Ensure we have at least 2 neighbors
        if len(neighbors) < 2:
            return np.array([index, index])

        # Select 2 random different neighbors
        selected = np.random.choice(neighbors, 2, replace=False)

        # Map the subproblem indices back to the agent indices
        return np.array([idx % space.n_agents for idx in selected])

    def _genetic_operators(self, parent1: Agent, parent2: Agent) -> tuple:
        """Applies genetic operators.

        Args:
            parent1: First parent.
            parent2: Second parent.

        Returns:
            (tuple): Two generated children.

        """

        p1_copy = copy.deepcopy(parent1)
        p2_copy = copy.deepcopy(parent2)
        
        # Apply crossover 
        children = self.crossover_operator(p1_copy, p2_copy)

        mutated_children = []
       
        # Apply Mutation
        for  child in children:
            actual_child = child[0] if isinstance(child, list) else child
            child_clone = copy.deepcopy(actual_child)
            mutated = self.mutation_operator(child_clone)

            mutated_children.append(mutated)
        # Return children
        return mutated_children

    def _update_neighborhood(
        self, index: int, new_agents: np.ndarray, new_f_values: np.ndarray, space: _MultiObjectiveSpace
    ) -> None:
        """Updates the population in the neighborhood.

        Args:
            index: Current agent index.
            new_agents: Newly generated agents.
            new_f_values: Fitness values of new agents.
            space: Space containing the population.

        """
        # Map the agent index to the subproblem index
        subproblem_idx = index % self.n_subproblems

        for i in self.T[subproblem_idx]:
            # Map the subproblem index to the agent index
            agent_idx = i % space.n_agents
            
            # Calculate fitness using decomposition
            fitness = np.array(
                [
                    self.decomposition_method(fit=f_value, weights=self.weight_vectors[i], z=self.z, penalty = self.pbi_penalty)
                    for f_value in new_f_values
                ]
            )

            

            # Current fitness
            actual_f_value = space.agents[agent_idx].fit
            actual_fitness = self.decomposition_method(fit=actual_f_value, weights=self.weight_vectors[i], z=self.z, penalty = self.pbi_penalty)
            

            # Update if better
            better_idx = np.argmin(fitness)
            
            if fitness[better_idx] <= actual_fitness:
                space.agents[agent_idx].position = copy.deepcopy(
                    new_agents[better_idx].position
                )
                space.agents[agent_idx].fit = copy.deepcopy(new_f_values[better_idx])

    def evaluate(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Evaluates the fitness of the agents.

        Args:
            space: Space containing agents and evaluation-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # Initial evaluation (first iteration)
        if self._is_first_iteration == True:
            for agent in space.agents:
                agent.fit = function(agent.position).squeeze()
                self.z = np.minimum(self.z, agent.fit)

            self._is_first_iteration = False

        
        # Update Pareto front
        #space.update_pareto_front()

    def update(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Updates the population using MOEA/D.

        Args:
            space: Space containing agents and update-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # For each agent in the population
        for index, agent in enumerate(space.agents):
            # Select neighbors
            selected = self._select_neighbors(index, space)
            parent1 = space.agents[selected[0]]
            parent2 = space.agents[selected[1]]
            
            # Apply genetic operators
            children = self._genetic_operators(parent1, parent2)
            
            # Evaluate new agents
            new_f_values = np.array([function(off.position).squeeze() for off in children])
            
            # Update reference point
            self.z = np.minimum(self.z, np.min(new_f_values, axis=0))
            
            # Update population in neighborhood
            self._update_neighborhood(index, children, new_f_values, space)


# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

@dataclass
class _MOEADCuda(MultiObjectiveOptimizer, MOEAD, backend=Backend.CUDA):
    """
        GPU-friendly implementation of MOEA/D
        based on the following work:
        Z. Liang, H. Li, N. Yu, K. Sun and R. Cheng, "Bridging Evolutionary Multiobjective Optimization and GPU Acceleration via Tensorization,"
        in IEEE Transactions on Evolutionary Computation, vol. 30, no. 1, pp. 420-434, Feb. 2026, doi: 10.1109/TEVC.2025.3555605.
    """

    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        crossover_operator=None,
        mutation_operator=None,
        weight_vectors=None,
        decomposition_method =  tchebycheff,
        pbi_penalty: float = 5.0,
        **kwargs
    ) -> None:
        """Initialization method.

        Args:
            params: Contains key-value parameters to the meta-heuristics.
            crossover_operator: Crossover operator to be used.
            mutation_operator: Mutation operator to be used.
            weight_vectors: Weights generated by utils.weight_vectors methods
            decomposition_method: The decomposition method reference (avaliables methods on `utils.decompostion`)
            pbi_penalty: PBI penalty, only required with pbi `decomposition_method`

        """
        logger.info("Overriding class: Optimizer -> MOEAD (Cuda).")

        super().__init__()

        self.n_subproblems = None
        self.neighborhood_size = None
        self.crossover_operator = crossover_operator or SBXCrossover()
        self.mutation_operator = mutation_operator or PolynomialMutation()
        self.decomposition_method = decomposition_method
        self.pbi_penalty = pbi_penalty
        self.weight_vectors = weight_vectors

        self.build(params)

        logger.info("Class overrided.")

    @property
    def n_subproblems(self) -> int:
        """Number of subproblems."""
        return self._n_subproblems

    @n_subproblems.setter
    def n_subproblems(self, n_subproblems: Optional[int]) -> None:
        if n_subproblems is not None:
            if not isinstance(n_subproblems, int):
                raise e.TypeError("`n_subproblems` should be an integer.")
            if n_subproblems <= 0:
                raise e.ValueError("`n_subproblems` should be higher than 0.")

        self._n_subproblems = n_subproblems


    @property
    def neighborhood_size(self) -> int:
        """Size of neighborhood T."""
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Optional[int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise e.TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise e.ValueError("`neighborhood_size` should be higher than 1.")

        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> Any:
        """Neighborhood of each subproblem."""
        return self._T
    @T.setter
    def T(self, T: Any) -> None:
        self._T = T
        
    @property
    def pbi_penalty(self) -> float:
        return self._pbi_penalty
    
    @pbi_penalty.setter
    def pbi_penalty(self, value: float) -> None:
            if not isinstance(value, (int, float)):
                raise e.TypeError('`pbi_penalty` should be a numeric value')
            if isinstance(value, int): value = float(value)
            
            if value < 0.0:
                raise e.ValueError('`pbi_penalty` should be an non-negative number')
            
            self._pbi_penalty = value


    @property
    def weight_vectors(self) -> Any:
        """Normalized weights vector."""
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: Any) -> None:
        self._weight_vectors = weights

    @property
    def z(self) ->Any:
        """Reference point."""
        return self._z

    @z.setter
    def z(self, ref: Any) -> None:
        self._z = ref

    def compile(self, space: _MultiObjectiveSpace, **kwargs) -> None:
        """Compiles additional information that is used by this optimizer.
        Args:
            space: A Space object containing meta-information.

        """

        if self.n_subproblems is None:
            self.n_subproblems = space.n_agents

        if self.neighborhood_size is None:
            self.neighborhood_size = max(2, int(space.env.xp.ceil(self.n_subproblems * 0.2)))

        self.weight_vectors = space.env.xp.array(self.weight_vectors)
        self.crossover_operator.env = space.env
        self.mutation_operator.env = space.env

        self._build_neighborhood(space.env.xp)
        self._build_neighborhood(space.env.xp)

        self.z = space.env.xp.full(space.n_objectives, space.env.xp.inf)
        self._is_first_iteration = True


        
    def _build_neighborhood(self, xp) -> None:
        """"""
        diff = self.weight_vectors[:, xp.newaxis, :] - self.weight_vectors[xp.newaxis, :, :]
        dist_matrix = xp.sqrt(xp.sum(diff ** 2, axis=2))
        
        self.T = xp.argsort(dist_matrix, axis=1)[:, :self.neighborhood_size]

    def evaluate(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """
       
        """
        xp = space.env.xp
        if self._is_first_iteration:
           
            X_init = xp.stack([agent.position.ravel() for agent in space.agents])
            
           
            F_init = function(X_init, xp=xp)
           
            
            
            for i, agent in enumerate(space.agents):
                agent.fit = F_init[i].tolist()

            
            self.z = xp.minimum(self.z, xp.min(F_init, axis=0))
            self._is_first_iteration = False

    def _mating_selection(self, space: _MultiObjectiveSpace) -> tuple:
        """
        """
        xp = space.env.xp
        
        rand_idx = xp.random.randint(0, self.neighborhood_size, size=(self.n_subproblems, 2))
        
       
        rows = xp.arange(self.n_subproblems)[:, xp.newaxis]
        neighbors_idx = self.T[rows, rand_idx] 
        
        parent1_indices = (neighbors_idx[:, 0] % space.n_agents).tolist()
        parent2_indices = (neighbors_idx[:, 1] % space.n_agents).tolist()
        
        
        parents1 = [space.agents[idx] for idx in parent1_indices]
        parents2 = [space.agents[idx] for idx in parent2_indices]
        
        return parents1, parents2

    def update(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """
        """

        xp = space.env.xp

        X = xp.stack([agent.position.ravel() for agent in space.agents])
        F = xp.stack([agent.fit for agent in space.agents])

        
        parents1, parents2 = self._mating_selection(space)
        children = self.crossover_operator(parents1, parents2)
        offspring = self.mutation_operator(children) 
        
        O = offspring.tensor[:self.n_subproblems] 

        F2 = function(O, xp=xp)

        
        self.z = xp.minimum(self.z, xp.min(F2, axis=0))

        
        for j in range(self.neighborhood_size):
            
            Inb = self.T[:, j] % space.n_agents
            
            
            W_nb = self.weight_vectors[self.T[:, j]]
            F_nb = F[Inb]
            
           
            g_old = self.decomposition_method(fit=F_nb, weights=W_nb, z=self.z, penalty=self.pbi_penalty, xp=xp)
            
           
            g_new = self.decomposition_method(fit=F2, weights=W_nb, z=self.z, penalty=self.pbi_penalty, xp=xp)
            
           
            mask = (g_new <= g_old).astype(xp.float32)
           
            mask_X = xp.expand_dims(mask, axis=1)
            mask_F = xp.expand_dims(mask, axis=1)
            
            
            X[Inb] = mask_X * O + (1.0 - mask_X) * X[Inb]
            F[Inb] = mask_F * F2 + (1.0 - mask_F) * F[Inb]


        X_cpu = X.tolist()
        F_cpu = F.tolist()
        for i, agent in enumerate(space.agents):
            agent.position = xp.array(X_cpu[i]).reshape(agent.position.shape)
            agent.fit = F_cpu[i]



# ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class MOEAD_DE(MultiObjectiveOptimizer):
    """MOEA/D-DE class, inherited from Optimizer.

    References:
        Li, H., & Zhang, Q. (2008). Multiobjective optimization problems with complicated Pareto sets, MOEA/D and NSGA-II.
        IEEE transactions on evolutionary computation, 13(2), 284-302.

    """
    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        CR: Union[float, int] = 1.0,
        nr: int = 2,
        F: Union[float, int] = 0.5,
        neighborhood_prob: float = 0.9,
        mutation_operator=None,
        weight_vectors=None,
        decomposition_function=tchebycheff,
        pbi_penalty: float = 5.0

    ) -> None:
        """Initialization method.

        Args:
            params: Contains key-value parameters to the meta-heuristics.
            mutation_operator: Mutation operator to be used.
            weight_vectors: Weights vector to be used.

        """
        logger.info("Overriding class: Optimizer -> MOEA/D-DE.")
        
        super().__init__()
        self.n_subproblems = None
        self.mutation_operator = mutation_operator or PolynomialMutation(rate=1/30, eta=20)
        self.weight_vectors = weight_vectors
        self.decomposition_function = decomposition_function
        self.CR = CR
        self.F = F
        self.nr = nr
        self.neighborhood_prob = neighborhood_prob
        self.neighborhood_size = 20
        self.pbi_penalty = pbi_penalty

        self.build(params)

        logger.info("Class overrided.")


    @property
    def CR(self) -> Union[float, int]:
        return self._CR
    
    @CR.setter
    def CR(self, rate: Union[float, int]) -> None:
        if not isinstance(rate, (float, int)):
            raise e.TypeError('`CR` should be an integer or float')
        
        if rate < 0.0 or rate > 1.0:
            raise e.ValueError('`CR` should be in [0, 1] interval')
        
        self._CR = rate

    @property
    def nr(self) -> int:
        """Maximun number of replacements in the mating pool"""
        return self._nr

    @nr.setter
    def nr(self, nr: int) -> None:
        if not isinstance(nr, int):
            raise e.TypeError("`nr` should be an integer.")
        if nr < 1:
            raise e.ValueError("`nr` should be greater equal than 1.")
        self._nr = nr

   
    @property
    def F(self) -> float:
        """The scalling factor"""
        return self._F

    @F.setter
    def F(self, F) -> None:
        if not isinstance(F, (float, int)):
            raise e.TypeError("`F` should be a float or an integer.")
        if F <= 0:
            raise e.ValueError("`F` should be greater than 0.")
        self._F = F

        
    @property
    def neighborhood_prob(self) -> Union[float, int]:
        return self._neighborhood_prob
    
    @neighborhood_prob.setter
    def neighborhood_prob(self, prob: Union[float, int]) -> None:
        if not isinstance(prob, (int, float)):
            raise e.TypeError('`neighborhood_prob` should be an integer or float')
        
        if prob < 0 or prob > 1:
            raise e.ValueError('`neighborhood_prob` should be in [0,1] interval')
        
        self._neighborhood_prob = prob
        
        
    @property
    def n_subproblems(self) -> int:
        """Number of subproblems."""
        return self._n_subproblems

    @n_subproblems.setter
    def n_subproblems(self, n_subproblems: Optional[int]) -> None:
        if n_subproblems is not None:
            if not isinstance(n_subproblems, int):
                raise e.TypeError("`n_subproblems` should be an integer.")
            if n_subproblems <= 0:
                raise e.ValueError("`n_subproblems` should be higher than 0.")

        self._n_subproblems = n_subproblems


    @property
    def neighborhood_size(self) -> Union[float, int]:
        """Size of neighborhood T."""
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Union[float,int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise e.TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise e.ValueError("`neighborhood_size` should be at least 2 agents.")

        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> np.ndarray:
        """Neighborhood of each subproblem."""
        return self._T

    @T.setter
    def T(self, T: np.ndarray) -> None:
        if not isinstance(T, np.ndarray):
            raise e.TypeError("`T` should be a numpy array.")
        self._T = T

    @property
    def weight_vectors(self) -> np.ndarray:
        """Normalized weights vector."""
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: np.ndarray) -> None:
        if not isinstance(weights, np.ndarray):
            weights = np.array(weights)
        self._weight_vectors = weights

    @property
    def z(self) -> np.ndarray:
        """Reference point."""
        return self._z

    @z.setter
    def z(self, ref: np.ndarray) -> None:
        if not isinstance(ref, np.ndarray):
            ref = np.array(ref)
        self._z = ref
        
    @property
    def decomposition_function(self):
        return self._decomposition_function
    
    @decomposition_function.setter
    def decomposition_function(self, decomposition_function)->None:
        
        self._decomposition_function = decomposition_function
        
        
    @property
    def pbi_penalty(self) -> float:
        return self._pbi_penalty
    
    @pbi_penalty.setter
    def pbi_penalty(self, value: float) -> None:
            if not isinstance(value, (int, float)):
                raise e.TypeError('`pbi_penalty` should be a numeric value')
            if isinstance(value, int): value = float(value)
            
            if value < 0.0:
                raise e.ValueError('`pbi_penalty` should be an non-negative number')
            
            self._pbi_penalty = value
        
        
        
    def compile(self, space: _MultiObjectiveSpace, **kwargs) -> None:
        """Compiles additional information that is used by this optimizer.

        Args:
            space: A Space object containing meta-information.

        """
        # If n_subproblems is not defined, use the number of agents
        if self.n_subproblems is None:
            self.n_subproblems = space.n_agents

        # Build neighborhood
        self._build_neighborhood()

        # Initialize reference point
        self.z = np.full(space.n_objectives, np.inf)

        # Initialize iteration counter
        self._aux_iteration = 0

    def _build_neighborhood(self) -> None:
        """Builds the neighborhood using Euclidean distance."""
        n = len(self.weight_vectors)
        distances = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                distances[i, j] = g.euclidean_distance(
                    self.weight_vectors[i], self.weight_vectors[j]
                )

        self.T = np.argsort(distances, axis=1)[:, :self.neighborhood_size]
        

    def _select_neighbors(self, mating_pool: np.ndarray) -> np.ndarray:
        """Selects neighbors for reproduction.

        Args:
            mating_pool: Current agent mating pool.
            space: Space containing the population.

        Returns:
            (np.ndarray): Selected neighbor indices.

        """

        # Ensure we have at least 2 neighbors
        if len(mating_pool) < 2:
            return np.array([mating_pool[0], mating_pool[0]])

        # Select 2 random different neighbors
        selected = np.random.choice(mating_pool, 2, replace=False)

        # Map the subproblem indices back to the agent indices
        return selected

    def _DE_operator(
        self,
        parent1: Agent,
        parent2: Agent,
        parent3: Agent,
    ) -> Agent:
        """Applies DE operator.
        Args:
            parent1: First parent.
            parent2: Second parent.
            parent3: Third parent
            space: Space containing boundary information

        Returns:
            np.ndarray: mutated solution position
        """

        mutant = copy.deepcopy(parent1)
        mutant.position = parent1.position + self.F * (parent2.position - parent3.position)
        
        mutation_mask = np.random.rand(mutant.n_variables,1) < self.CR
        
        positions = np.where(mutation_mask, mutant.position, parent1.position)
        
        mutant.position = positions
        mutant.position = np.clip(mutant.position, mutant.lb.reshape(-1,1), mutant.ub.reshape(-1,1))
        
        return mutant
        
        

    def _apply_operators(
        self,
        parent1: Agent,
        parent2: Agent,
        parent3: Agent,
    ) -> Agent:
        """Applies DE and genetic operator.

        Args:
            parent1: First parent.
            parent2: Second parent.
            parent3: Third parent
            space: Space containing boundary information.

        Returns:
            np.ndarray: The generated children position.

        """

        # Apply DE operator
        child = self._DE_operator(
            parent1=parent1, parent2=parent2, parent3=parent3
        )
        
        child = self.mutation_operator(child)

        return child

    def _update_neighborhood(
        self,
        new_agent: Agent,
        space: _MultiObjectiveSpace,
        mating_pool: np.ndarray,
    ) -> None:
        """Updates the population in the neighborhood.

        Args:
            new_agents: Newly generated agents.
            new_f_values: Fitness values of new agents.
            space: Space containing the population.
            mating_pool: Current agent mating pool.
        """

        c = 0

        while c < self.nr and len(mating_pool) > 0:

            i = np.random.choice(mating_pool, 1).item()

            # Calculate fitness using decomposition
            fitness = np.array(self.decomposition_function(fit=new_agent.fit, weights=self.weight_vectors[i], z=self.z, penalty=self.pbi_penalty))

            # Current fitness
            current_agent = space.agents[i]
            current_fitness = self.decomposition_function(fit=current_agent.fit, weights=self.weight_vectors[i], z=self.z, penalty=self.pbi_penalty)

            # Update if better

            if fitness <= current_fitness:
                current_agent.position = copy.deepcopy(new_agent.position)
                current_agent.fit = copy.deepcopy(new_agent.fit)
                c += 1

            # Remove the index from mating pool

            idx = np.where(mating_pool == i)[0][0]
            mating_pool = np.delete(mating_pool, idx)

    def _build_mating_pool(self, index) -> np.ndarray:
        """Build the mating of each agent"""
        """
        Args:
            index: current agent index.
        Returns:
            The agent mating pool
        """

        if np.random.rand() < self.neighborhood_prob:
            return self.T[index].copy()
        else:
            return np.array([i for i in range(self.n_subproblems)])


    def evaluate(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Evaluates the fitness of the agents.

        Args:
            space: Space containing agents and evaluation-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # Initial evaluation (first iteration)
        if self._aux_iteration == 0:
            for agent in space.agents:
                agent.fit = function(agent.position).flatten()
                self.z = np.minimum(self.z, agent.fit)

            self._aux_iteration = 1

        # Update Pareto front
        space.update_pareto_front(space.agents)


    def update(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Updates the population using MOEA/D.

        Args:
            space: Space containing agents and update-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # For each agent in the population
        for index, agent in enumerate(space.agents):
            
            parent1 = copy.deepcopy(agent)
            # Build the mating pool
            mating_pool = self._build_mating_pool(index)

            # Select neighbors
            selected = self._select_neighbors(mating_pool)
            
            parent2, parent3 = copy.deepcopy(space.agents[selected[0]]), copy.deepcopy(space.agents[selected[1]]) 

            # Apply DE and polynomial mutation
            
            offspring = self._apply_operators(parent1, parent2, parent3)

            # Evaluate new agents
            offspring.fit = function(offspring.position)

            # Update reference point
            self.z = np.minimum(self.z, offspring.fit)

            # Update population in neighborhood
            self._update_neighborhood(offspring, space, mating_pool)