"""MOEA/D."""

import copy
from typing import Any, Dict, Optional, Union, Tuple, List

import numpy as np

from opytimizer.core import Environment
import opytimizer.math.general as g
import opytimizer.utils.exception as e
from opytimizer.core.agent import Agent
from opytimizer.core.function import Function
from opytimizer.core import MultiObjectiveOptimizer, TensorizedMultiObjectiveOptimizer
from opytimizer.core.space import _MultiObjectiveSpace, _MultiObjectiveTensorSpace
from opytimizer.utils import logging
from opytimizer.math.aggregation import  Tchebycheff, PBI, _BaseAggregation
from opytimizer.utils.operators import PolynomialMutation, SBXCrossover, PolynomialMutationTensor, SBXCrossoverTensor


logger = logging.get_logger(__name__)



class MOEAD(MultiObjectiveOptimizer):
    """MOEAD class, inherited from Optimizer.

    References:
        Zhang, Q., & Li, H. (2007). MOEA/D: A multiobjective evolutionary algorithm based on decomposition.
        IEEE Transactions on evolutionary computation, 11(6), 712-731.

    """

    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        crossover_operator=None,
        mutation_operator=None,
        weight_vectors=None,
        neighborhood_size: int = None,
        decomposition_method: _BaseAggregation =  None,
        **kwargs
    ) -> None:
        """Initialization method.

        Args:
            params: Contains key-value parameters to the meta-heuristics.
            crossover_operator: Crossover operator to be used.
            mutation_operator: Mutation operator to be used.
            weight_vectors: Weights generated by utils.weight_vectors methods
            decomposition_method: The decomposition method reference (avaliables methods on `utils.math.aggregation`)
            

        """
        logger.info("Overriding class: Optimizer -> MOEAD (Default).")

        super().__init__()

        self.neighborhood_size = neighborhood_size
        self.crossover_operator = crossover_operator or SBXCrossover(n_offspring=1)
        self.mutation_operator = mutation_operator or PolynomialMutation()
        self.decomposition_method = decomposition_method or Tchebycheff()
        self.weight_vectors = weight_vectors

        self.build(params)

        self.T = None # neighborhood index array
    
        logger.info("Class overrided.")



    @property
    def neighborhood_size(self) -> int:
        """Size of neighborhood T."""
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Optional[int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise e.TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise e.ValueError("`neighborhood_size` should be higher than 1.")

        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> np.ndarray:
        """Neighborhood of each subproblem."""
        return self._T
    @T.setter
    def T(self, T: np.ndarray) -> None:
        self._T = T
        

    @property
    def weight_vectors(self) -> np.ndarray:
        """Normalized weights vector."""
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: np.ndarray) -> None:
        if not isinstance(weights, np.ndarray):
            weights = np.array(weights)
        self._weight_vectors = weights

    @property
    def z(self) -> np.ndarray:
        """Reference point."""
        return self._z

    @z.setter
    def z(self, ref: np.ndarray) -> None:
        if not isinstance(ref, np.ndarray):
            ref = np.array(ref)
        self._z = ref


    
    def _build_neighborhood(self) -> None:
        dists = np.sum(self.weight_vectors**2, axis=1, keepdims=True) - 2 * np.dot(self.weight_vectors, self.weight_vectors.T) + np.sum(self.weight_vectors**2, axis=1)
        dists = np.maximum(dists, 0)
        neighbors = np.argpartition(dists, kth=self.neighborhood_size, axis=1)[:, :self.neighborhood_size]

        rows = np.arange(neighbors.shape[0])[:, None]
        sorted_neighbors = neighbors[rows, np.argsort(dists[rows, neighbors], axis=1)]

        self.T = sorted_neighbors


    def _parents_indices_selection(self, subproblem_index: int) -> Tuple[int, int]:
        """Returns the parents indices"""

        parents_indices = np.random.choice(self.T[subproblem_index], 2, replace=False)
        return parents_indices[0], parents_indices[1]


    def _genetic_operators(self, P1: Agent, P2: Agent) -> Union[Agent, List[Agent]]:
        
        offspring = self.crossover_operator(P1, P2)

        if isinstance(offspring, tuple):
            # two offsprings
            child_1, child_2 = offspring
            child_1, child_2 = self.mutation_operator(child_1[0]), self.mutation_operator(child_2[0])
            return [child_1, child_2]
        else:
            #one offspring
            child_1 = self.mutation_operator(offspring)
            return child_1

    def _environmental_selection(self, children: List[Agent], subproblem_index: int, space: _MultiObjectiveSpace) -> None:
        
        neighbors = self.T[subproblem_index]
        
        weights = self.weight_vectors[neighbors]
        neighbors_fit = np.array([space.agents[idx].fit for idx in neighbors])
        
        current_pop_aggr = self.decomposition_method(neighbors_fit, weights, np, z=self.z)

        children_aggr = np.array([
            self.decomposition_method(child.fit, weights, np, z=self.z) 
            for child in children
        ])

       
        best_child_indices = np.argmin(children_aggr, axis=0)
        best_child_aggr = np.min(children_aggr, axis=0)
        
        replace_mask = best_child_aggr <= current_pop_aggr

        for i, neighbor_index in enumerate(neighbors):
            if replace_mask[i]:
                selected_agent = children[best_child_indices[i]]
                space.agents[neighbor_index].position = selected_agent.position.copy()
                space.agents[neighbor_index].fit = selected_agent.fit.copy()
        
    def compile(self, space: _MultiObjectiveSpace):
        
        if self.neighborhood_size is None: self.neighborhood_size = int(0.2 * space.n_agents)

        self._build_neighborhood()

        self.z = np.full(shape=space.n_objectives, fill_value=np.inf)



    def evaluate(self, space: _MultiObjectiveSpace, function: Function) -> None:
        
        # Initial evaluation -> then this function will be overrided
        for agent in space.agents:
            agent.fit = function(agent.position)
            self.z = np.minimum(self.z, agent.fit)

        

        self.evaluate = lambda : None


    def update(self, space: _MultiObjectiveSpace, function: Function) -> None:
        # main loop
        
        #subproblems permutation -> avoids update bias
        subproblems_order = np.random.permutation(space.n_agents)

        for sub_problem_index in subproblems_order:
            p_1_index, p_2_index = self._parents_indices_selection(sub_problem_index)
            children = self._genetic_operators(space.agents[p_1_index], space.agents[p_2_index])

            fits = []
            for child in children:
                child.fit = function(child.position)
                fits.append(child.fit) 
            
            self.z = np.minimum(self.z, np.min(fits, axis=0))
            
            self._environmental_selection(children, sub_problem_index, space)



# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class MOEADTensor(MultiObjectiveOptimizer, TensorizedMultiObjectiveOptimizer):
    """
        Tensorized implementation of MOEA/D
        based on the following work:
        Z. Liang, H. Li, N. Yu, K. Sun and R. Cheng, "Bridging Evolutionary Multiobjective Optimization and GPU Acceleration via Tensorization,"
        in IEEE Transactions on Evolutionary Computation, vol. 30, no. 1, pp. 420-434, Feb. 2026, doi: 10.1109/TEVC.2025.3555605.
    """

    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        crossover_operator=None,
        mutation_operator=None,
        weight_vectors=None,
        decomposition_method: _BaseAggregation =  None,
        **kwargs
    ) -> None:
        """Initialization method."""
        logger.info("Overriding class: Optimizer -> MOEAD (Tensor).")

        super().__init__()

        self.n_subproblems = None
        self.neighborhood_size = None
        self.crossover_operator = crossover_operator or SBXCrossoverTensor(env=Environment('numpy', 'float32'))
        self.mutation_operator = mutation_operator or PolynomialMutationTensor(env=Environment('numpy', 'float32'))
        self.decomposition_method = decomposition_method or PBI()
        self.weight_vectors = weight_vectors

        self.build(params)

        logger.info("Class overrided.")

    @property
    def n_subproblems(self) -> int:
        return self._n_subproblems

    @n_subproblems.setter
    def n_subproblems(self, n_subproblems: Optional[int]) -> None:
        if n_subproblems is not None:
            if not isinstance(n_subproblems, int):
                raise TypeError("`n_subproblems` should be an integer.")
            if n_subproblems <= 0:
                raise ValueError("`n_subproblems` should be higher than 0.")
        self._n_subproblems = n_subproblems

    @property
    def neighborhood_size(self) -> int:
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Optional[int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise ValueError("`neighborhood_size` should be higher than 1.")
        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> Any:
        return self._T
        
    @T.setter
    def T(self, T: Any) -> None:
        self._T = T

    @property
    def weight_vectors(self) -> Any:
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: Any) -> None:
        self._weight_vectors = weights

    @property
    def z(self) -> Any:
        return self._z

    @z.setter
    def z(self, ref: Any) -> None:
        self._z = ref

    def compile(self, space: _MultiObjectiveTensorSpace, **kwargs) -> None:
        """Compiles additional information that is used by this optimizer."""
        if self.n_subproblems is None:
            self.n_subproblems = space.n_agents

        if self.neighborhood_size is None:
            self.neighborhood_size = max(2, int(space.env.xp.ceil(self.n_subproblems * 0.2)))

        self.weight_vectors = space.env.xp.array(self.weight_vectors)
        self.crossover_operator.env = space.env
        self.mutation_operator.env = space.env

        self._build_neighborhood(space.env.xp)

        self.z = space.env.xp.full(space.n_objectives, space.env.xp.inf)

    def _build_neighborhood(self, xp) -> None:
        diff = self.weight_vectors[:, xp.newaxis, :] - self.weight_vectors[xp.newaxis, :, :]
        dist_matrix = xp.sqrt(xp.sum(diff ** 2, axis=2))
        self.T = xp.argsort(dist_matrix, axis=1)[:, :self.neighborhood_size]


    def evaluate(self, space: _MultiObjectiveTensorSpace, function: Function) -> None:
        xp = space.env.xp
        
     
        
        space.F = function(space.X, xp=xp)
            
        self.z = xp.minimum(self.z, xp.min(space.F, axis=0))

        self.evaluate = lambda args: None
           


    def _mating_selection(self, space: _MultiObjectiveTensorSpace) -> Tuple:
        xp = space.env.xp
        
        rand_idx = xp.random.randint(0, self.neighborhood_size, size=(self.n_subproblems, 2))
        rows = xp.arange(self.n_subproblems)[:, xp.newaxis]
        neighbors_idx = self.T[rows, rand_idx] 
        
        parent1_indices = neighbors_idx[:, 0] % space.n_agents
        parent2_indices = neighbors_idx[:, 1] % space.n_agents
        
        
        parents1_X = space.X[parent1_indices]
        parents2_X = space.X[parent2_indices]
        
        return parents1_X, parents2_X

    def update(self, space: _MultiObjectiveTensorSpace, function: Function) -> None:
        xp = space.env.xp

        
        parents1_X, parents2_X = self._mating_selection(space)
        
        
        child1_X, child2_X = self.crossover_operator(parents1_X, parents2_X, space.lb, space.ub)
        del child2_X
        offspring_X = self.mutation_operator(child1_X, space.lb, space.ub) 
        
        
        O = offspring_X[:self.n_subproblems]
        
        F2 = function(O, xp=xp)

        
        self.z = xp.minimum(self.z, xp.min(F2, axis=0))

      
        targets = self.T.flatten() % space.n_agents 
        
        
        O_exp = xp.repeat(O, self.neighborhood_size, axis=0)
        F2_exp = xp.repeat(F2, self.neighborhood_size, axis=0)
        
        
        F_nb = space.F[targets]
        W_nb = self.weight_vectors[targets]
        
        
        g_old = self.decomposition_method(F_nb, W_nb, xp, z=self.z)
        g_new = self.decomposition_method(F2_exp, W_nb, xp, z=self.z)
        
    
        mask = g_new <= g_old
        
       
        valid_targets = targets[mask]
        valid_O = O_exp[mask]
        valid_F2 = F2_exp[mask]
        valid_g_new = g_new[mask]
        
        
        sort_idx = xp.argsort(valid_g_new)
        valid_targets = valid_targets[sort_idx]
        valid_O = valid_O[sort_idx]
        valid_F2 = valid_F2[sort_idx]
        
        _, unique_indices = xp.unique(valid_targets, return_index=True)
        final_targets = valid_targets[unique_indices]
        final_O = valid_O[unique_indices]
        final_F2 = valid_F2[unique_indices]

        space.X[final_targets] = final_O
        space.F[final_targets] = final_F2
        

# ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


class MOEAD_DE(MultiObjectiveOptimizer):
    """MOEA/D-DE class, inherited from Optimizer.

    References:
        Li, H., & Zhang, Q. (2008). Multiobjective optimization problems with complicated Pareto sets, MOEA/D and NSGA-II.
        IEEE transactions on evolutionary computation, 13(2), 284-302.

    """
    def __init__(
        self,
        params: Optional[Dict[str, Any]] = None,
        CR: Union[float, int] = 1.0,
        nr: int = 2,
        F: Union[float, int] = 0.5,
        neighborhood_prob: float = 0.9,
        mutation_operator=None,
        weight_vectors=None,
        decomposition_function: _BaseAggregation = None,

    ) -> None:
        """Initialization method.

        Args:
            params: Contains key-value parameters to the meta-heuristics.
            mutation_operator: Mutation operator to be used.
            weight_vectors: Weights vector to be used.

        """
        logger.info("Overriding class: Optimizer -> MOEA/D-DE.")
        
        super().__init__()
        self.n_subproblems = None
        self.mutation_operator = mutation_operator or PolynomialMutation()
        self.weight_vectors = weight_vectors
        self.decomposition_function = decomposition_function or Tchebycheff()
        self.CR = CR
        self.F = F
        self.nr = nr
        self.neighborhood_prob = neighborhood_prob
        self.neighborhood_size = 20

        self.build(params)

        logger.info("Class overrided.")


    @property
    def CR(self) -> Union[float, int]:
        return self._CR
    
    @CR.setter
    def CR(self, rate: Union[float, int]) -> None:
        if not isinstance(rate, (float, int)):
            raise e.TypeError('`CR` should be an integer or float')
        
        if rate < 0.0 or rate > 1.0:
            raise e.ValueError('`CR` should be in [0, 1] interval')
        
        self._CR = rate

    @property
    def nr(self) -> int:
        """Maximun number of replacements in the mating pool"""
        return self._nr

    @nr.setter
    def nr(self, nr: int) -> None:
        if not isinstance(nr, int):
            raise e.TypeError("`nr` should be an integer.")
        if nr < 1:
            raise e.ValueError("`nr` should be greater equal than 1.")
        self._nr = nr

   
    @property
    def F(self) -> float:
        """The scalling factor"""
        return self._F

    @F.setter
    def F(self, F) -> None:
        if not isinstance(F, (float, int)):
            raise e.TypeError("`F` should be a float or an integer.")
        if F <= 0:
            raise e.ValueError("`F` should be greater than 0.")
        self._F = F

        
    @property
    def neighborhood_prob(self) -> Union[float, int]:
        return self._neighborhood_prob
    
    @neighborhood_prob.setter
    def neighborhood_prob(self, prob: Union[float, int]) -> None:
        if not isinstance(prob, (int, float)):
            raise e.TypeError('`neighborhood_prob` should be an integer or float')
        
        if prob < 0 or prob > 1:
            raise e.ValueError('`neighborhood_prob` should be in [0,1] interval')
        
        self._neighborhood_prob = prob
        
        
    @property
    def n_subproblems(self) -> int:
        """Number of subproblems."""
        return self._n_subproblems

    @n_subproblems.setter
    def n_subproblems(self, n_subproblems: Optional[int]) -> None:
        if n_subproblems is not None:
            if not isinstance(n_subproblems, int):
                raise e.TypeError("`n_subproblems` should be an integer.")
            if n_subproblems <= 0:
                raise e.ValueError("`n_subproblems` should be higher than 0.")

        self._n_subproblems = n_subproblems


    @property
    def neighborhood_size(self) -> Union[float, int]:
        """Size of neighborhood T."""
        return self._neighborhood_size

    @neighborhood_size.setter
    def neighborhood_size(self, neighborhood_size: Union[float,int]) -> None:
        if neighborhood_size is not None:
            if not isinstance(neighborhood_size, int):
                raise e.TypeError("`neighborhood_size` should be an integer.")
            if neighborhood_size < 2:
                raise e.ValueError("`neighborhood_size` should be at least 2 agents.")

        self._neighborhood_size = neighborhood_size

    @property
    def T(self) -> np.ndarray:
        """Neighborhood of each subproblem."""
        return self._T

    @T.setter
    def T(self, T: np.ndarray) -> None:
        if not isinstance(T, np.ndarray):
            raise e.TypeError("`T` should be a numpy array.")
        self._T = T

    @property
    def weight_vectors(self) -> np.ndarray:
        """Normalized weights vector."""
        return self._weight_vectors

    @weight_vectors.setter
    def weight_vectors(self, weights: np.ndarray) -> None:
        if not isinstance(weights, np.ndarray):
            weights = np.array(weights)
        self._weight_vectors = weights

    @property
    def z(self) -> np.ndarray:
        """Reference point."""
        return self._z

    @z.setter
    def z(self, ref: np.ndarray) -> None:
        if not isinstance(ref, np.ndarray):
            ref = np.array(ref)
        self._z = ref
        
    @property
    def decomposition_function(self):
        return self._decomposition_function
    
    @decomposition_function.setter
    def decomposition_function(self, decomposition_function)->None:
        
        self._decomposition_function = decomposition_function
        
             
    def compile(self, space: _MultiObjectiveSpace, **kwargs) -> None:
        """Compiles additional information that is used by this optimizer.

        Args:
            space: A Space object containing meta-information.

        """
        # If n_subproblems is not defined, use the number of agents
        if self.n_subproblems is None:
            self.n_subproblems = space.n_agents

        # Build neighborhood
        self._build_neighborhood()

        # Initialize reference point
        self.z = np.full(space.n_objectives, np.inf)

        # Initialize iteration counter
        self._aux_iteration = 0

    def _build_neighborhood(self) -> None:
        """Builds the neighborhood using Euclidean distance."""
        n = len(self.weight_vectors)
        distances = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                distances[i, j] = g.euclidean_distance(
                    self.weight_vectors[i], self.weight_vectors[j]
                )

        self.T = np.argsort(distances, axis=1)[:, :self.neighborhood_size]
        

    def _select_neighbors(self, mating_pool: np.ndarray) -> np.ndarray:
        """Selects neighbors for reproduction.

        Args:
            mating_pool: Current agent mating pool.
            space: Space containing the population.

        Returns:
            (np.ndarray): Selected neighbor indices.

        """

        # Ensure we have at least 2 neighbors
        if len(mating_pool) < 2:
            return np.array([mating_pool[0], mating_pool[0]])

        # Select 2 random different neighbors
        selected = np.random.choice(mating_pool, 2, replace=False)

        # Map the subproblem indices back to the agent indices
        return selected

    def _DE_operator(
        self,
        parent1: Agent,
        parent2: Agent,
        parent3: Agent,
    ) -> Agent:
        """Applies DE operator.
        Args:
            parent1: First parent.
            parent2: Second parent.
            parent3: Third parent
            space: Space containing boundary information

        Returns:
            np.ndarray: mutated solution position
        """
       
        mutant = copy.deepcopy(parent1)
        mutant.position = parent1.position + self.F * (parent2.position - parent3.position)
        
        mutation_mask = np.random.rand(mutant.n_variables,1) < self.CR
        
        positions = np.where(mutation_mask, mutant.position, parent1.position)
        
        mutant.position = positions
        mutant.position = np.clip(mutant.position, mutant.lb.reshape(-1,1), mutant.ub.reshape(-1,1))
        
        return mutant
        
        

    def _apply_operators(
        self,
        parent1: Agent,
        parent2: Agent,
        parent3: Agent,
    ) -> Agent:
        """Applies DE and genetic operator.

        Args:
            parent1: First parent.
            parent2: Second parent.
            parent3: Third parent
            space: Space containing boundary information.

        Returns:
            np.ndarray: The generated children position.

        """

        # Apply DE operator
        child = self._DE_operator(
            parent1=parent1, parent2=parent2, parent3=parent3
        )
        
        child = self.mutation_operator(child)

        return child

    def _update_neighborhood(
        self,
        new_agent: Agent,
        space: _MultiObjectiveSpace,
        mating_pool: np.ndarray,
    ) -> None:
        """Updates the population in the neighborhood.

        Args:
            new_agents: Newly generated agents.
            new_f_values: Fitness values of new agents.
            space: Space containing the population.
            mating_pool: Current agent mating pool.
        """

        c = 0

        while c < self.nr and len(mating_pool) > 0:

            i = np.random.choice(mating_pool, 1).item()

            # Calculate fitness using decomposition
            fitness = np.array(self.decomposition_function(new_agent.fit, self.weight_vectors[i], np, z=self.z,))

            # Current fitness
            current_agent = space.agents[i]
            current_fitness = self.decomposition_function(current_agent.fit, self.weight_vectors[i], np, z=self.z)

            # Update if better

            if fitness <= current_fitness:
                current_agent.position = copy.deepcopy(new_agent.position)
                current_agent.fit = copy.deepcopy(new_agent.fit)
                c += 1

            # Remove the index from mating pool

            idx = np.where(mating_pool == i)[0][0]
            mating_pool = np.delete(mating_pool, idx)

    def _build_mating_pool(self, index) -> np.ndarray:
        """Build the mating of each agent"""
        """
        Args:
            index: current agent index.
        Returns:
            The agent mating pool
        """

        if np.random.rand() < self.neighborhood_prob:
            return self.T[index].copy()
        else:
            return np.array([i for i in range(self.n_subproblems)])


    def evaluate(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Evaluates the fitness of the agents.

        Args:
            space: Space containing agents and evaluation-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # Initial evaluation (first iteration)
        if self._aux_iteration == 0:
            for agent in space.agents:
                agent.fit = function(agent.position).flatten()
                self.z = np.minimum(self.z, agent.fit)

            self._aux_iteration = 1

       

    def update(self, space: _MultiObjectiveSpace, function: Function) -> None:
        """Updates the population using MOEA/D.

        Args:
            space: Space containing agents and update-related information.
            function: Function to evaluate the fitness of the agents.

        """
        # For each agent in the population
        for index, agent in enumerate(space.agents):
            
            parent1 = copy.deepcopy(agent)
            
            # Build the mating pool
            mating_pool = self._build_mating_pool(index)

            # Select neighbors
            selected = self._select_neighbors(mating_pool)
            
            parent2, parent3 = copy.deepcopy(space.agents[selected[0]]), copy.deepcopy(space.agents[selected[1]]) 

            # Apply DE and polynomial mutation
            
            offspring = self._apply_operators(parent1, parent2, parent3)

            # Evaluate new agents
            offspring.fit = function(offspring.position)

            # Update reference point
            self.z = np.minimum(self.z, offspring.fit)

            # Update population in neighborhood
            self._update_neighborhood(offspring, space, mating_pool)